version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x

    commands:
      cd cccr-frontend
      npm install
  build:
    commands:
      cd cccr-frontend
      npm run build

artifacts:
  files:
    - '**/*'
  base-directory: cccr-frontend/build
